Fix readme

diff --git a/aws_mfa_me b/aws_mfa_me
--- a/aws_mfa_me
+++ b/aws_mfa_me
@@ -5,22 +5,22 @@ if [[ -z $(command -v jq) ]]; then
     return 1
 fi
 
-echo 'Getting MFA ARN (assuming first device)...'
-mfa_arn=$(aws iam list-mfa-devices | jq -r ".MFADevices[0].SerialNumber")
-if [[ $? != 0 ]]; then
-    echo 'Failed to get MFA device ARN'
-    return 1
+duration=${duration:-129600}
+mfa_arn=${mfa_arn:-}
+
+if [[ -z $mfa_arn ]]; then
+    echo 'Getting MFA ARN (assuming first device)...'
+    mfa_arn=$(aws iam list-mfa-devices | jq -r ".MFADevices[0].SerialNumber")
 fi
 
-_prompt() {
-    read input
-    echo $input
-}
+if [[ $? != 0 ]]; then
+    echo 'Failed to get MFA device ARN'
+    exit 1
+fi
 
-echo -n "Enter MFA code: "
-mfa_code=$(_prompt)
-
-duration=${1:-129600}
+echo -n "Enter MFA code for device $mfa_arn: "
+read mfa_code
+echo ""
 
 # Clear env vars if session credentials already set
 if [[ ! -z $AWS_SESSION_TOKEN ]]; then
@@ -33,7 +33,7 @@ fi
 aws_creds=$(aws sts get-session-token --serial-number $mfa_arn --token-code $mfa_code --duration-seconds $duration)
 if [[ $? != 0 ]]; then
     echo 'Failed to get AWS credentials'
-    return 1
+    exit 1
 fi
 
 export AWS_ACCESS_KEY_ID=$(jq -r ".Credentials.AccessKeyId" <<< $aws_creds)
